### ISSUE TITLE
Docker  Build Does not work

### ISSUE THREAD

**Issue by kecondezo** [madflojo/redis-tls-dockerfile#7]
Guys your docker file does not  run with a build it show an error "pip module not found" I solved this using this Dockerfile besed from yours

```FROM redis:6-alpine

RUN apk add --no-cache \
    stunnel \
    python3 \
    py3-pip

RUN python3 -m pip install honcho==1.0.*

WORKDIR /
COPY stunnel.conf ProcfileWithoutPwd ProcfileWithPwd start.sh /
RUN chmod +x start.sh

ENV PYTHONUNBUFFERED=1
CMD ["sh", "start.sh"]
```
The start.sh is wrong too, when I set re REDIS_PASS the shell is calling the profile without password I fix using this start.sh based from yours
```#!/bin/bash

if [ -z "$REDIS_PASS" ]
then
    honcho start -f ProcfileWithoutPwd
else
    honcho start -f ProcfileWithPwd
fi
```

**Comment by madflojo** [comment]
Fixed this, also added a travis build file in the repo so that it will catch issues like this pre-merge.
